import datetime
from .structs import *

__all__ = ['FinanceiroAPI']

API_CODE_ERROR = int

class FinanceiroAPI:
    def isConnected(self) -> bool: ...
    def isLogged(self) -> bool: ...

    def login(self, username:str, password:str) -> bool: ...
    def connect(self, **db_params) -> bool: ...
    def checkCredentials(self, username:str, password:str) -> bool: ...

    def updateObject(self, instance_of_obj:AbstractTable) -> None: ...
    def deleteObject(self, instance_of_obj:AbstractTable) -> None: ...
    def countTable(self, typeof:AbstractTable) -> int: ...
    def getValuesWithNavigation(self, typeof:AbstractTable, index_interval:int) -> tuple[AbstractTable]: ...

    # create
    def createUser(self, username:str, password:str, first_name:str, last_name:str) -> User: ...
    def createBank(self, name:str, description:str|None=...) -> Bank: ...
    def createCard(self, num:int, dia_fechamento:int, dia_vencimento:int, limite:int, bank_id:int) -> Card: ...
    def createRegistry(self, type:REG_TYPE, title:str, value:float, datetime:datetime.datetime, description:str|None=..., bank_id:int|None=..., card_id:int|None=...) -> Registry: ...

    # get
    def getCurrentUser(self) -> User | None: ...
    def getNavigationTableInfo(self, typeof:AbstractTable) -> NavigationTableInfo: ...
    def getUser(self, id:int) -> User: ...
    def getBank(self, id:int) -> Bank: ...
    def getCard(self, id:int) -> Card: ...
    def getRegistry(self, id:int) -> Registry: ...
