import datetime
from .structs import *

__all__ = ['FinanceiroAPI']

API_CODE_ERROR = int

class FinanceiroAPI:
    def login(self, username:str, password:str) -> bool: ...
    def checkCredentials(self, username:str, password:str) -> bool: ...
    def connect(self, **db_params) -> bool: ...
    def isConnected(self) -> bool: ...

    # create
    def createUser(self, username:str, password:str, first_name:str, last_name:str) -> User: ...
    def createBank(self, name:str, description:str|None=...) -> Bank: ...
    def createCard(self, num:int, dia_fechamento:int, dia_vencimento:int, limite:int, bank_id:int) -> Card: ...
    def createRegistry(self, type:REG_TYPE, title:str, value:float, datetime:datetime.datetime, description:str|None=..., bank_id:int|None=..., card_id:int|None=...) -> Registry: ...

    # get
    def getCurrentUser(self) -> User: ...
    def getUser(self, id:int) -> User: ...
    def getBank(self, id:int) -> Bank: ...
    def getCard(self, id:int) -> Card: ...
    def getRegistry(self, id:int) -> Registry: ...

    def updateObject(self, obj:AbstractTable) -> None: ...
    def deleteObject(self, obj:AbstractTable) -> None: ...