import datetime
from typing import Literal
from .structs import *
from .consts import DB_ROWS_LIMIT

__all__ = ['FinanceiroAPI']

API_CODE_ERROR = int

class FinanceiroAPI:
    def __init__(self, db_engine:Literal['sqlite3', 'mysql']): ...
    
    def isConnected(self) -> bool: ...
    def isLogged(self) -> bool: ...

    def login(self, username:str, password:str) -> bool: ...
    def connect(self, filename:str) -> bool: ...
    def checkCredentials(self, username:str, password:str) -> bool: ...

    def updateObject(self, instance_of_obj:AbstractTable) -> None: ...
    def deleteObject(self, instance_of_obj:AbstractTable) -> None: ...
    def countTable(self, typeof:AbstractTable) -> int: ...

    # create
    def createUser(self, username:str, password:str, first_name:str, last_name:str) -> User: ...
    def createBank(self, name:str, description:str|None=...) -> Bank: ...
    def createCard(self, num:int, dia_fechamento:int, dia_vencimento:int, limite:int, bank_id:int) -> Card: ...
    def createRegistry(self, type:REG_TYPE, title:str, value:float, datetime:datetime.datetime, description:str|None=..., bank_id:int|None=..., card_id:int|None=...) -> Registry: ...

    # get
    def getCurrentUser(self) -> User | None: ...
    def getObject(self, id:int, typeof:AbstractTable) -> AbstractTable: ...
    # def getAllObjects(self, typeof:AbstractTable) -> list[AbstractTable]: ...
    def getUser(self, id:int) -> User: ...
    def getBank(self, id:int) -> Bank: ...
    def getCard(self, id:int) -> Card: ...
    def getRegistry(self, id:int) -> Registry: ...
    def getNavigationTableInfo(self, typeof:AbstractTable, interval=0, limit=DB_ROWS_LIMIT) -> NavigationTableInfo: ...
    def getValuesByIndexInterval(self, typeof:AbstractTable, *, index_interval=0, info:NavigationTableInfo|None=...) -> tuple[NavigationTableInfo, list[AbstractTable]]: ...
    
    def getAllBanks(self) -> list[Bank]: ...
    def getAllRegistries(self) -> list[Registry]: ...
    def getCardsByBankId(self, bank_id:int) -> list[Card]: ...
